### ISSUE TITLE
yolov3 怎么转snpe 的dlc了解吗

### ISSUE THREAD

**Issue by fanzy1234** [gesanqiu/Ericsson-Yolov3-SNPE#1]
可以留个联系方式吗？请教下如何把训练好的yolo模型转dlc

**Comment by gesanqiu** [comment]
正常使用SNPE提供的snpe-onnx-to-dlc完成的转换，如果遇到问题，可以请教算法部门的人员或者给高通的NPU team提case以获取支持。

**Comment by fanzy1234** [comment]
再麻烦问下，您的Python版本，onnx版本和snpe版本是多少呢？
我试了多个版本还是不行

---原始邮件---
发件人: "Ricardo ***@***.***&gt;
发送时间: 2021年12月14日(周二) 上午10:01
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [gesanqiu/Ericsson-Yolov3-SNPE] yolov3 怎么转snpe 的dlc了解吗 (Issue #1)




 
正常使用SNPE提供的snpe-onnx-to-dlc完成的转换，如果遇到问题，可以请教算法部门的人员或者给高通的NPU team提case以获取支持。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
