### ISSUE TITLE
算法DSP并行效率

### ISSUE THREAD

**Issue by fwzdev1** [gesanqiu/Ericsson-Yolov3-SNPE#2]
您好，谢谢您的分享，十分受用。
有一个点我很好奇：

> 算法使用的是Qualcomm的SNPE DL框架，根据之前开发的测试得知DSP实例最多可以起七个，AIP实例可以起10个，各个实例之间相互效率影响并不大，于是就想到通过并行运行算法，设计一个缓冲池，同时处理多张图片，再一次性送显示，于是就有了v2的设计。

想问问您这一块的详细情况，影响不大的程度大概是怎样？ 因为我目前的任务是轻量化算法，所以对时间影响很敏感。多谢了！

**Comment by gesanqiu** [comment]
你好，

v2的repo发布于半年前，那时候的我对snpe的理解还不太深入，这个结论在现在看来并不太严谨，我当时只是写了个for循环不断去new thread和snpe对象，new到第十个aip实例的时候会报错，仅此而已。至于你说的影响，我写了个profile工具去打印多实例下的耗时，做了个简单benchmark，DSP在跑满的情况下推理耗时将翻倍，AIP大概增加10%，要获取time cost的数据并不难。

按我目前的理解，UserBuffer实际是ION buffer，用于(gpu/)dsp/aip与user space通信，而ION的内存据我同事说大约是2-3GB，具体SNPE能用多少还取决于很多因素（比如GPU，甚至是内核BSP层面的限制），于是我觉得能够初始化多少个实例与模型以及它需要的buffer有关。在后续我们改进推理架构做了更加精细的memory manage之后，跑一些小的模型极限能够初始化二十多个dsp/aip runtime instances，当然二十多个也不是极限，因为我的程序还有其他模块会消耗ion buffer。

谢谢。

**Comment by fwzdev1** [comment]
> 你好，
> 
> v2的repo发布于半年前，那时候的我对snpe的理解还不太深入，这个结论在现在看来并不太严谨，我当时只是写了个for循环不断去new thread和snpe对象，new到第十个aip实例的时候会报错，仅此而已。至于你说的影响，我写了个profile工具去打印多实例下的耗时，做了个简单benchmark，DSP在跑满的情况下推理耗时将翻倍，AIP大概增加10%，要获取time cost的数据并不难。
> 
> 按我目前的理解，UserBuffer实际是ION buffer，用于(gpu/)dsp/aip与user space通信，而ION的内存据我同事说大约是2-3GB，具体SNPE能用多少还取决于很多因素（比如GPU，甚至是内核BSP层面的限制），于是我觉得能够初始化多少个实例与模型以及它需要的buffer有关。在后续我们改进推理架构做了更加精细的memory manage之后，跑一些小的模型极限能够初始化二十多个dsp/aip runtime instances，当然二十多个也不是极限，因为我的程序还有其他模块会消耗ion buffer。
> 
> 谢谢。

谢谢！非常详细的解答了！祝您工作顺利~

**Comment by fwzdev1** [comment]
> 你好，
> 
> v2的repo发布于半年前，那时候的我对snpe的理解还不太深入，这个结论在现在看来并不太严谨，我当时只是写了个for循环不断去new thread和snpe对象，new到第十个aip实例的时候会报错，仅此而已。至于你说的影响，我写了个profile工具去打印多实例下的耗时，做了个简单benchmark，DSP在跑满的情况下推理耗时将翻倍，AIP大概增加10%，要获取time cost的数据并不难。
> 
> 按我目前的理解，UserBuffer实际是ION buffer，用于(gpu/)dsp/aip与user space通信，而ION的内存据我同事说大约是2-3GB，具体SNPE能用多少还取决于很多因素（比如GPU，甚至是内核BSP层面的限制），于是我觉得能够初始化多少个实例与模型以及它需要的buffer有关。在后续我们改进推理架构做了更加精细的memory manage之后，跑一些小的模型极限能够初始化二十多个dsp/aip runtime instances，当然二十多个也不是极限，因为我的程序还有其他模块会消耗ion buffer。
> 
> 谢谢。

您好，突然想起来，您的那么多instance是每个分别用一个thread跑的吗？虽说能建这么多起来但是thread的数量够吗？

**Comment by gesanqiu** [comment]
> 

一个thread一个inference instance。
